### ISSUE TITLE
Updates of lmiwbem.config are not applied

### ISSUE THREAD

**Issue by alexanderlaw** [phatina/python-lmiwbem#22]
It's impossible to disable default trust store with lmiwbem 0.7.1.
lmiwbem.config.DEFAULT_TRUST_STORE = ''
- has no effect.
As I see in lmiwbem_config.cpp s_inst_ptr used in Config::defaultTrustStore references Config object that is not the same as the one created in init_type.

**Comment by phatina** [comment]
Thank you, I will fix it soon.

**Comment by phatina** [comment]
Please, verify.

**Comment by alexanderlaw** [comment]
Yes, now it works. Thank you!

**Comment by phatina** [comment]
Thank you. I am considering a release now; do you have anything to fix/include?

**Comment by alexanderlaw** [comment]
Please look at https://github.com/phatina/python-lmiwbem/issues/23
I think the fix is simple.
